import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Layout from "@/components/Layout";
import Image from "next/image";
import ProfilePic from "../../public/images/profile/developer-pic-1.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-ful min-h-screen">
        <Layout>
          <div className="flex items-center justify-between w-full">
            <div>
              <Image src={ProfilePic} alt="OliverWu" className="w-full h-auto" />
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}
